name: dart_utils
description: A collection of useful helpers for Dart providing solutions for different situations.
version: 1.0.1
author: Jesway <hello@jesway.com>
homepage: https://github.com/jesway/dart_utils

environment:
  sdk: '>=2.5.0 <3.0.0'
