name: dart_utils
description: A collection of useful helpers for Dart providing solutions for different situations.
version: 2.0.0
homepage: https://bratan.me
repository: https://github.com/bratan/dart_utils

environment:
  sdk: '>=2.12.0 <3.0.0'
